name: Frontend CI

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  
jobs:
  lint-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json 

    - name: Restore node_modules cache
      uses: actions/cache@v3
      with:
        path: starter/frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('starter/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm ci

    - name: Lint
      run: |
        cd starter/frontend        
        npm run lint

  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Restore node_modules cache
      uses: actions/cache@v3
      with:
        path: starter/frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('starter/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm ci

    - name: Test
      run: |
        cd starter/frontend        
        npm run test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Restore node_modules cache
      uses: actions/cache@v3
      with:
        path: starter/frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('starter/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm ci

    - name: Build Project
      run: |
        cd starter/frontend        
        npm run test
    
    - name: Build Docker Image
      run: |
        cd starter/frontend        
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://backend.default.svc.cluster.local --tag=mp-frontend:latest .