name: Frontend CI

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  
jobs:
  lint-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
       run: ls -la starter/frontend

    - name: Restore node_modules cache
      uses: actions/cache@v3
      with:
        path: starter/frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('starter/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm install

    - name: lint
      run: |
        cd starter/frontend        
        npm run lint

  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'

    - name: Restore node_modules cache
      uses: actions/cache@v3
      with:
        path: starter/frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('starter/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm install

    - name: test
      run: |
        cd starter/frontend        
        npm run test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'

    - name: Restore node_modules cache
      uses: actions/cache@v3
      with:
        path: starter/frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('starter/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm install

    - name: build
      run: |
        cd starter/frontend        
        npm run test
